spring:
  application:
    name: delivery
    environment: local
  datasource:
    url: jdbc:mysql://localhost:3306/micro_delivery
    username: local
    password: Secret12!@
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog.yaml
jwt:
  secret: MySecretKeyMySecretKeyMySecretKey!
  expiration: 3600000